[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.toc]
permalink =  true

[project.theme]
logo = "Images/logo_new_filled.png"
favicon = "Images/favicon.png"
features = [
  "content.action.edit",
  "content.action.view",
	"navigation.path"
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon-star"
toggle.name = "Switch to system preferences"

[project.theme.icon]
repo = "fontawesome/brands/github"
edit = "material/pencil"
view = "material/eye"

[project]
site_name = "Wiki"
site_url = "https://wiki.rusefi.com/"
repo_url = "https://github.com/rusefi/rusefi"
repo_name = "rusefi/rusefi"
edit_uri = "https://github.com/rusefi/rusefi_documentation/edit/master/"
site_dir = "wiki"
extra_css = ["stylesheets/extra.css"]

nav = [
  {"Downloads" = "Download.md"},
  {"Getting Started" = [
    {"Quick Start" = "HOWTO-quick-start.md"},
    {"Support & Community" = "Support.md"},
    {"How to create a TunerStudio project" = "HOWTO-create-tunerstudio-project.md"},
    {"rusEFI Online" = "Online.md"},
    {"HOWTOs and FAQs" = "Pages-FAQ-and-HOWTO.md"}
  ]},
  {"Features" = [
    {"Fueling" = "Fuel-Overview.md"},
    {"Cranking" = "Cranking.md"},
    {"Electronic Throttle" = "Electronic-Throttle-Body-Configuration-Guide.md"},
    {"Knock Sensing" = "knock-sensing.md"},
    {"Variable Valve Timing" = "VVT.md"},
    {"Lua Scripting" = "Lua-Scripting.md"},
    {"GDI" = "GDI-status.md"},
    {"Digital Dash" = "Digital-Dash.md"},
    {"Wideband Oxygen Sensors" = "Wide-Band-Sensors.md"},
    {"Multispark" = "Multi-Spark.md"}
  ]},
  {"Setup Guides" = [
    {"Trigger - Configuration" = "Trigger-Configuration-Guide.md"},
    {"Trigger - Setting Offset" = "How-Do-I-Set-My-Trigger-Offset.md"},
    {"Electronic Throttle Body" = "Electronic-Throttle-Body-Configuration-Guide.md"},
    {"Logging" = "Logging-Guide.md"}
  ]},
  {"Pages" = [
    {"Fuel" = "Pages-Fuel.md"},
    {"Flex Fuel" = "Flex-Fuel.md"},
    {"Sensors and Actuators" = "Pages-Sensors-and-Actuators.md"},
    {"Ignition" = "Pages-Ignition.md"},
    {"Software" = "Pages-Software.md"}
  ]},
  {"Hardware" = [
    {"rusEFI Hardware Overview" = "Hardware.md"},
    {"Wiring & Connectivity Overview" = "FAQ-Basic-Wiring-and-Connections.md"},
    {"Wire-in ECUs" = [
      {"uaEFI" = "uaEFI.md"},
      {"microRusEFI" = "Hardware-microRusEFI.md"},
      {"Proteus" = "Proteus.md"}
    ]},
    {"Plug & Play ECUs" = [
      {"Honda OBD1" = "uaEFI-Honda-OBD1.md"},
      {"GM E38" = "GM-E38.md"},
      {"GM E92" = "PnP-E92.md"},
      {"Hellen" = "Hellen-One-Platform.md"}
    ]}
  ]},
  {"Developers" = [
    {"Contribute to Firmware" = "HOWTO-contribute-to-firmware.md"},
    {"Contribute to Documentation" = "HOWTO-contribute-to-documentation.md"}
  ]}
]