#
# ACCESS_TOKEN - Personal Access Token with "public_repo" permission
# If there is a change to rusefi/rusefi_documentation, this action merges it to rusefi/rusefi/wiki
#
# the opposite merge is implemented as https://github.com/rusefi/rusefi/blob/master/.github/workflows/sync-wiki.yaml
#

name: Sync Wiki

on:
  push:
    branches:
    - master

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'actions-user' }}

    steps:
    - name: Check out docs repo
      uses: actions/checkout@v2

    - name: Install Prerequisites
      run: |
        sudo apt update
        sudo apt install ncftp
        pip install mkdocs mkdocs-ezlinks-plugin


    - name: Generate static pages
      run: |
        cd mkdocs
        

    - name: Set FTP variables
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        if [ "${{github.ref}}" = "refs/heads/master" ]; then
          echo "::set-env name=RUSEFI_FTP_SERVER::${{secrets.RUSEFI_FTP_SERVER}}";
          echo "::set-env name=RUSEFI_DOXYGEN_FTP_USER::${{secrets.RUSEFI_DOXYGEN_FTP_USER}}";
          echo "::set-env name=RUSEFI_DOXYGEN_FTP_PASS::${{secrets.RUSEFI_DOXYGEN_FTP_PASS}}";
        fi

    - name: Upload results
      run: |
        cd mkdocs/
        mv site wiki
        if [ -n "$RUSEFI_FTP_SERVER" ]; then
          echo "Uploading Wiki"
          ncftpput -R -z -m -V -u "$RUSEFI_DOXYGEN_FTP_USER" -p "$RUSEFI_DOXYGEN_FTP_PASS" "$RUSEFI_FTP_SERVER" / wiki
        fi
        [ $? -eq 0 ] || { echo "upload FAILED"; exit 1; }
