site_name: rusEFI Wiki
site_url: https://wiki.rusefi.com/
repo_url: https://github.com/rusefi/rusefi_documentation
edit_uri: edit/master/
theme: 
  name: readthedocs
  collapse_navigation: true
plugins:
  - search
  - ezlinks:
      wikilinks: true
  - exclude:
      glob:
        - mkdocs/*

markdown_extensions:
  - sane_lists
  - md_in_html
  - toc:
      permalink: True
  - pymdownx.magiclink

extra_css:
  - style.css

nav:
  - 'Downloads': Download.md
  - 'Getting Started':
    - 'Quick Start': HOWTO-quick-start.md
    - 'How to ask questions': HOWTO-ask-questions.md
    - 'Support': Support.md
    - 'How to create a TunerStudio project': HOWTO-create-tunerstudio-project.md
    - 'HOWTOs and FAQs': Pages-FAQ-and-HOWTO.md
  - 'Community':
    - 'Forum': "https://rusefi.com/forum/"
    - 'Discord': Discord.md
    - 'Engines running on rusEFI': List-of-Engines-Running-rusEFI.md
    - 'HOWTO-help-rusEFI': HOWTO-help-rusEFI.md
  - 'Setup Guides':
    - 'Trigger - Configuration': Trigger-Configuration-Guide.md
    - 'Trigger - Setting Offset': How-Do-I-Set-My-Trigger-Offset.md
    - 'Electronic Throttle Body': Electronic-Throttle-Body-Configuration-Guide.md
  - 'Pages':
    - 'Fuel': Pages-Fuel.md
    - 'Flex Fuel': Flex-Fuel.md
    - 'Hardware': Hardware.md
    - 'Sensors and Actuators': Pages-Sensors-and-Actuators.md
    - 'Ignition': Pages-Ignition.md
    - 'How To': Pages-HOWTO.md
  - 'Features':
    - 'rusEFI Online': Online.md
    - 'rusEFI virtual simulator': Virtual-simulator.md
    - 'Fueling': Fuel-Overview.md
    - 'Multispark': Multi-Spark.md
    - 'Cranking': Cranking.md
    - 'Electronic Throttle': Electronic-Throttle-Body-Configuration-Guide.md
    - 'Knock Sensing': knock-sensing.md
    - 'Variable Valve Timing': VVT.md
    - 'Lua': Lua-Scripting.md
    - 'GDI': GDI-status.md
    - 'Digital Dash': Digital-Dash.md
  - 'Hardware':
    - 'rusEFI Hardware Overview': Hardware.md
    - 'Wiring & Connectivity Overview': FAQ-Basic-Wiring-and-Connections.md
    - 'Boards':
      - 'Proteus': Proteus.md
      - 'MicroRusEFI (MRE)': Hardware-microRusEFI.md
  - 'Misc':
    - 'Do I need a wideband oxygen sensor?': do-i-need-wideband-oxygen-sensor.md
