site_name: rusEFI Wiki
site_url: https://wiki.rusefi.com/
repo_url: https://github.com/rusefi/rusefi_documentation
edit_uri: edit/master/
theme: 
  name: readthedocs
  collapse_navigation: true
plugins:
  - search
  - ezlinks:
      wikilinks: true
markdown_extensions:
  - sane_lists
nav:
  - 'Home': Home
  - 'Downloads': Download
  - 'Getting Started':
    - 'How to search the Wiki': HOWTO/HOWTO-Search-on-rusEFI-wiki
    - 'Quick Start': HOWTO/HOWTO-quick-start
    - 'How to ask questions': HOWTO/HOWTO-ask-questions
    - 'Support': Support/Support
    - 'How to create a TunerStudio project': HOWTO/HOWTO-create-tunerstudio-project
    - 'HOWTOs and FAQs': FAQ/Pages-FAQ-and-HOWTO
  - 'Community':
    - 'Forum': "https://rusefi.com/forum/"
    - 'Slack': HOWTO/HOWTO-join-slack-channel
    - 'Engines running on rusEFI': List-of-Engines-Running-rusEFI
    - 'HOWTO-help-rusEFI': HOWTO/HOWTO-help-rusEFI
  - 'Setup Guides':
    - 'Trigger - Configuration': Trigger-Configuration-Guide
    - 'Trigger - Setting Offset': FAQ/How-Do-I-Set-My-Trigger-Offset
    - 'Electronic Throttle Body': Electronic-Throttle-Body-Configuration-Guide
  - 'Pages':
    - 'Fuel': Fuel/Pages-Fuel
    - 'Flex Fuel': Fuel/Flex-Fuel
    - 'Hardware': Hardware/Pages-Hardware
    - 'Sensors and Actuators': HOWTO/Pages-Sensors-and-Actuators
    - 'Ignition': Spark/Pages-Ignition
    - 'Software': HOWTO/Pages-Software
    - 'TunerStudio Views': Overview/TS_generated/rusEFI-project
    - 'How To': HOWTO/Pages-HOWTO
  - 'Features':
    - 'rusEFI Online': HOWTO/Online
    - 'rusEFI virtual simulator': HOWTO/Virtual-simulator
    - 'Fueling': Fuel/Fuel_Control/Fuel-Overview
    - 'Multispark': Spark/Multi-Spark
    - 'Cranking': HOWTO/Cranking
    - 'Electronic Throttle': Electronic-Throttle-Body-Configuration-Guide
    - 'Knock Sensing': Technical/knock-sensing
    - 'Variable Valve Timing': Technical/VVT
    - 'FSIO - Flexible Sweet Input Output': HOWTO/FSIO
    - 'GDI': FAQ/GDI-status
    - 'Digital Dash': Digital-Dash
  - 'Hardware':
    - 'rusEFI Hardware Overview': Hardware/Hardware
    - 'Wiring & Connectivity Overview': FAQ/FAQ-Basic-Wiring-and-Connections
    - 'rusEFI Assembly Completeness Chart': Hardware/Completeness-Chart
    - 'Kit Instructions': HOWTO/Pages-Kit-Instructions
    - 'Boards':
      - 'Hellen': Hellen-One-Platform
      - 'Proteus': Hardware/Proteus/Proteus
      - 'MicroRusEFI (MRE)': Hardware/microRusEFI/Hardware-microRusEFI
      - 'Frankenso': Hardware/Frankenso/Hardware-Frankenso
      - 'Frankenstein': Hardware/Frankenstein/Hardware-Frankenstein
    - 'Plug & Play Hardware':
      - 'Hellen Miata 90-95': Hardware/Hellen/Hellen64-Miata-NA6-94
      - 'Hellen Miata 01-05 VVT': Hardware/Hellen/Hellen72
      - 'MREAdapter55: from Lada to e30': Hardware/MREAdapter55
      - 'Frankenso MazdaMiataNA6 PnP': installations/MazdaMiataNA6_Frankenso_pnp/Frankenso-MazdaMiataNA6-pnp
      - 'Creating a PnP PCB': HOWTO/HOWTO-Make-a-PnP-board
  - 'Contributors':
    - 'Documentation Strategy': Documentation-Strategy
    - 'Documentation Workflow': Documentation-Workflow
    - 'Firmware Code Doxygen': "https://rusefi.com/docs/html"
    - 'Firmware Code Automated Test Coverage': "https://rusefi.com/docs/unit_tests_coverage"
    - 'HOWTO Contribute To Firmware': HOWTO/HOWTO-contribute-to-firmware
    - 'Firmware performance tracing': Dev/Developer-Performance-Tracing
    - 'Connector Mapping': Connector-Mapping
  - 'Misc':
    - 'How to convert from carburetor to EFI': FAQ/how-to-convert-from-carburetor-to-EFI
    - 'Do I need a wideband oxygen sensor?': FAQ/do-i-need-wideband-oxygen-sensor
